version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:v1.1.0
    container_name: alpha1
    working_dir: /data/alpha1
    labels:
      cluster: flock-cluster
    ports:
    - 8080:8080
    - 9080:9080
    volumes:
    - type: bind
      source: $DATA_DIR
      target: /data
      read_only: false
    command: dgraph alpha --my=alpha1:7080 --lru_mb=1024 --zero=zero1:5080
  zero1:
    image: dgraph/dgraph:v1.1.0
    container_name: zero1
    working_dir: /data/zero1
    labels:
      cluster: flock-cluster
    ports:
    - 5080:5080
    - 6080:6080
    volumes:
    - type: bind
      source: $DATA_DIR
      target: /data
      read_only: false
    command: dgraph zero --my=zero1:5080 --idx=1
  ratel:
    image: dgraph/dgraph:v1.1.0
    container_name: ratel
    labels:
      cluster: flock-cluster
    ports:
    - 8000:8000
    command: dgraph-ratel
